# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfindexeddb.leveldb.plugins.proto.chrome_sync import extension_specifics_pb2 as extension__specifics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pp_specifics.proto\x12\x07sync_pb\x1a\x19\x65xtension_specifics.proto\"`\n\x17\x41ppNotificationSettings\x12\x1a\n\x12initial_setup_done\x18\x01 \x01(\x08\x12\x10\n\x08\x64isabled\x18\x02 \x01(\x08\x12\x17\n\x0foauth_client_id\x18\x03 \x01(\t\".\n\x11LinkedAppIconInfo\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\r\"\xfc\x03\n\x0c\x41ppSpecifics\x12.\n\textension\x18\x01 \x01(\x0b\x32\x1b.sync_pb.ExtensionSpecifics\x12?\n\x15notification_settings\x18\x02 \x01(\x0b\x32 .sync_pb.AppNotificationSettings\x12\x1a\n\x12\x61pp_launch_ordinal\x18\x03 \x01(\t\x12\x14\n\x0cpage_ordinal\x18\x04 \x01(\t\x12\x35\n\x0blaunch_type\x18\x05 \x01(\x0e\x32 .sync_pb.AppSpecifics.LaunchType\x12\x18\n\x10\x62ookmark_app_url\x18\x06 \x01(\t\x12 \n\x18\x62ookmark_app_description\x18\x07 \x01(\t\x12\x1f\n\x17\x62ookmark_app_icon_color\x18\x08 \x01(\t\x12\x34\n\x10linked_app_icons\x18\t \x03(\x0b\x32\x1a.sync_pb.LinkedAppIconInfo\x12\x1a\n\x12\x62ookmark_app_scope\x18\n \x01(\t\x12 \n\x18\x62ookmark_app_theme_color\x18\x0b \x01(\r\"A\n\nLaunchType\x12\n\n\x06PINNED\x10\x00\x12\x0b\n\x07REGULAR\x10\x01\x12\x0e\n\nFULLSCREEN\x10\x02\x12\n\n\x06WINDOW\x10\x03\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _APPNOTIFICATIONSETTINGS._serialized_start=59
  _APPNOTIFICATIONSETTINGS._serialized_end=155
  _LINKEDAPPICONINFO._serialized_start=157
  _LINKEDAPPICONINFO._serialized_end=203
  _APPSPECIFICS._serialized_start=206
  _APPSPECIFICS._serialized_end=714
  _APPSPECIFICS_LAUNCHTYPE._serialized_start=649
  _APPSPECIFICS_LAUNCHTYPE._serialized_end=714
# @@protoc_insertion_point(module_scope)
