# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_list_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pp_list_specifics.proto\x12\x07sync_pb\"\xb7\x02\n\x10\x41ppListSpecifics\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12<\n\titem_type\x18\x02 \x01(\x0e\x32).sync_pb.AppListSpecifics.AppListItemType\x12\x11\n\titem_name\x18\x03 \x01(\t\x12\x11\n\tparent_id\x18\x04 \x01(\t\x12!\n\x15OBSOLETE_page_ordinal\x18\x05 \x01(\tB\x02\x18\x01\x12\x14\n\x0citem_ordinal\x18\x06 \x01(\t\x12\x18\n\x10item_pin_ordinal\x18\x07 \x01(\t\"[\n\x0f\x41ppListItemType\x12\x0c\n\x08TYPE_APP\x10\x01\x12\x1b\n\x17TYPE_REMOVE_DEFAULT_APP\x10\x02\x12\x0f\n\x0bTYPE_FOLDER\x10\x03\x12\x0c\n\x08TYPE_URL\x10\x04\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_list_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _APPLISTSPECIFICS.fields_by_name['OBSOLETE_page_ordinal']._options = None
  _APPLISTSPECIFICS.fields_by_name['OBSOLETE_page_ordinal']._serialized_options = b'\030\001'
  _APPLISTSPECIFICS._serialized_start=38
  _APPLISTSPECIFICS._serialized_end=349
  _APPLISTSPECIFICS_APPLISTITEMTYPE._serialized_start=258
  _APPLISTSPECIFICS_APPLISTITEMTYPE._serialized_end=349
# @@protoc_insertion_point(module_scope)
