# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_setting_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfindexeddb.leveldb.plugins.proto.chrome_sync import extension_setting_specifics_pb2 as extension__setting__specifics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x61pp_setting_specifics.proto\x12\x07sync_pb\x1a!extension_setting_specifics.proto\"T\n\x13\x41ppSettingSpecifics\x12=\n\x11\x65xtension_setting\x18\x01 \x01(\x0b\x32\".sync_pb.ExtensionSettingSpecificsB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_setting_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _APPSETTINGSPECIFICS._serialized_start=75
  _APPSETTINGSPECIFICS._serialized_end=159
# @@protoc_insertion_point(module_scope)
