# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61rticle_specifics.proto\x12\x07sync_pb\"\x98\x01\n\x10\x41rticleSpecifics\x12\x10\n\x08\x65ntry_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12#\n\x05pages\x18\x03 \x03(\x0b\x32\x14.sync_pb.ArticlePage\x12>\n\x0b\x61ttachments\x18\x04 \x01(\x0b\x32%.sync_pb.DeprecatedArticleAttachmentsB\x02\x18\x01\"\x1a\n\x0b\x41rticlePage\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x1e\n\x1c\x44\x65precatedArticleAttachmentsB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'article_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _ARTICLESPECIFICS.fields_by_name['attachments']._options = None
  _ARTICLESPECIFICS.fields_by_name['attachments']._serialized_options = b'\030\001'
  _ARTICLESPECIFICS._serialized_start=37
  _ARTICLESPECIFICS._serialized_end=189
  _ARTICLEPAGE._serialized_start=191
  _ARTICLEPAGE._serialized_end=217
  _DEPRECATEDARTICLEATTACHMENTS._serialized_start=219
  _DEPRECATEDARTICLEATTACHMENTS._serialized_end=249
# @@protoc_insertion_point(module_scope)
