# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attachments.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ttachments.proto\x12\x07sync_pb\"J\n\x11\x41ttachmentIdProto\x12\x11\n\tunique_id\x18\x01 \x01(\t\x12\x12\n\nsize_bytes\x18\x02 \x01(\x04\x12\x0e\n\x06\x63rc32c\x18\x03 \x01(\r\"X\n\x18\x41ttachmentMetadataRecord\x12&\n\x02id\x18\x01 \x01(\x0b\x32\x1a.sync_pb.AttachmentIdProto\x12\x14\n\x0cis_on_server\x18\x02 \x01(\x08\"G\n\x12\x41ttachmentMetadata\x12\x31\n\x06record\x18\x01 \x03(\x0b\x32!.sync_pb.AttachmentMetadataRecordB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attachments_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _ATTACHMENTIDPROTO._serialized_start=30
  _ATTACHMENTIDPROTO._serialized_end=104
  _ATTACHMENTMETADATARECORD._serialized_start=106
  _ATTACHMENTMETADATARECORD._serialized_end=194
  _ATTACHMENTMETADATA._serialized_start=196
  _ATTACHMENTMETADATA._serialized_end=267
# @@protoc_insertion_point(module_scope)
