# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookmark_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62ookmark_specifics.proto\x12\x07sync_pb\"&\n\x08MetaInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x92\x01\n\x11\x42ookmarkSpecifics\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0f\n\x07\x66\x61vicon\x18\x02 \x01(\x0c\x12\r\n\x05title\x18\x03 \x01(\t\x12\x18\n\x10\x63reation_time_us\x18\x04 \x01(\x03\x12\x10\n\x08icon_url\x18\x05 \x01(\t\x12$\n\tmeta_info\x18\x06 \x03(\x0b\x32\x11.sync_pb.MetaInfoB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookmark_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _METAINFO._serialized_start=37
  _METAINFO._serialized_end=75
  _BOOKMARKSPECIFICS._serialized_start=78
  _BOOKMARKSPECIFICS._serialized_end=224
# @@protoc_insertion_point(module_scope)
