# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_commands.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63lient_commands.proto\x12\x07sync_pb\"9\n\x10\x43ustomNudgeDelay\x12\x13\n\x0b\x64\x61tatype_id\x18\x01 \x01(\x05\x12\x10\n\x08\x64\x65lay_ms\x18\x02 \x01(\x05\"\xc0\x02\n\rClientCommand\x12\x1e\n\x16set_sync_poll_interval\x18\x01 \x01(\x05\x12#\n\x1bset_sync_long_poll_interval\x18\x02 \x01(\x05\x12\x1d\n\x15max_commit_batch_size\x18\x03 \x01(\x05\x12%\n\x1dsessions_commit_delay_seconds\x18\x04 \x01(\x05\x12\x1e\n\x16throttle_delay_seconds\x18\x05 \x01(\x05\x12,\n$client_invalidation_hint_buffer_size\x18\x06 \x01(\x05\x12\x1e\n\x16gu_retry_delay_seconds\x18\x07 \x01(\x05\x12\x36\n\x13\x63ustom_nudge_delays\x18\x08 \x03(\x0b\x32\x19.sync_pb.CustomNudgeDelayB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_commands_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _CUSTOMNUDGEDELAY._serialized_start=34
  _CUSTOMNUDGEDELAY._serialized_end=91
  _CLIENTCOMMAND._serialized_start=94
  _CLIENTCOMMAND._serialized_end=414
# @@protoc_insertion_point(module_scope)
