# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_info_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfindexeddb.leveldb.plugins.proto.chrome_sync import sync_enums_pb2 as sync__enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64\x65vice_info_specifics.proto\x12\x07sync_pb\x1a\x10sync_enums.proto\"\x8d\x02\n\x13\x44\x65viceInfoSpecifics\x12\x12\n\ncache_guid\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x32\n\x0b\x64\x65vice_type\x18\x03 \x01(\x0e\x32\x1d.sync_pb.SyncEnums.DeviceType\x12\x17\n\x0fsync_user_agent\x18\x04 \x01(\t\x12\x16\n\x0e\x63hrome_version\x18\x05 \x01(\t\x12\'\n\x1b\x64\x65precated_backup_timestamp\x18\x06 \x01(\x03\x42\x02\x18\x01\x12\x1f\n\x17signin_scoped_device_id\x18\x07 \x01(\t\x12\x1e\n\x16last_updated_timestamp\x18\x08 \x01(\x03\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_info_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _DEVICEINFOSPECIFICS.fields_by_name['deprecated_backup_timestamp']._options = None
  _DEVICEINFOSPECIFICS.fields_by_name['deprecated_backup_timestamp']._serialized_options = b'\030\001'
  _DEVICEINFOSPECIFICS._serialized_start=59
  _DEVICEINFOSPECIFICS._serialized_end=328
# @@protoc_insertion_point(module_scope)
