# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65ntity_metadata.proto\x12\x07sync_pb\"\x8b\x02\n\x0e\x45ntityMetadata\x12\x17\n\x0f\x63lient_tag_hash\x18\x01 \x01(\t\x12\x11\n\tserver_id\x18\x02 \x01(\t\x12\x12\n\nis_deleted\x18\x03 \x01(\x08\x12\x17\n\x0fsequence_number\x18\x04 \x01(\x03\x12\x1d\n\x15\x61\x63ked_sequence_number\x18\x05 \x01(\x03\x12\x1a\n\x0eserver_version\x18\x06 \x01(\x03:\x02-1\x12\x15\n\rcreation_time\x18\x07 \x01(\x03\x12\x19\n\x11modification_time\x18\x08 \x01(\x03\x12\x16\n\x0especifics_hash\x18\t \x01(\t\x12\x1b\n\x13\x62\x61se_specifics_hash\x18\n \x01(\tB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity_metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _ENTITYMETADATA._serialized_start=35
  _ENTITYMETADATA._serialized_end=302
# @@protoc_insertion_point(module_scope)
