# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extension_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65xtension_specifics.proto\x12\x07sync_pb\"\xea\x01\n\x12\x45xtensionSpecifics\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x12\n\nupdate_url\x18\x03 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x04 \x01(\x08\x12\x19\n\x11incognito_enabled\x18\x05 \x01(\x08\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x16\n\x0eremote_install\x18\x07 \x01(\x08\x12\x1e\n\x16installed_by_custodian\x18\x08 \x01(\x08\x12\x18\n\x10\x61ll_urls_enabled\x18\t \x01(\x08\x12\x17\n\x0f\x64isable_reasons\x18\n \x01(\x05\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extension_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _EXTENSIONSPECIFICS._serialized_start=39
  _EXTENSIONSPECIFICS._serialized_end=273
# @@protoc_insertion_point(module_scope)
