# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: favicon_image_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66\x61vicon_image_specifics.proto\x12\x07sync_pb\"=\n\x0b\x46\x61viconData\x12\x0f\n\x07\x66\x61vicon\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"\xf1\x01\n\x15\x46\x61viconImageSpecifics\x12\x13\n\x0b\x66\x61vicon_url\x18\x01 \x01(\t\x12)\n\x0b\x66\x61vicon_web\x18\x02 \x01(\x0b\x32\x14.sync_pb.FaviconData\x12,\n\x0e\x66\x61vicon_web_32\x18\x03 \x01(\x0b\x32\x14.sync_pb.FaviconData\x12.\n\x10\x66\x61vicon_touch_64\x18\x04 \x01(\x0b\x32\x14.sync_pb.FaviconData\x12:\n\x1c\x66\x61vicon_touch_precomposed_64\x18\x05 \x01(\x0b\x32\x14.sync_pb.FaviconDataB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'favicon_image_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _FAVICONDATA._serialized_start=42
  _FAVICONDATA._serialized_end=103
  _FAVICONIMAGESPECIFICS._serialized_start=106
  _FAVICONIMAGESPECIFICS._serialized_end=347
# @@protoc_insertion_point(module_scope)
