# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: favicon_tracking_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n favicon_tracking_specifics.proto\x12\x07sync_pb\"b\n\x18\x46\x61viconTrackingSpecifics\x12\x13\n\x0b\x66\x61vicon_url\x18\x01 \x01(\t\x12\x1a\n\x12last_visit_time_ms\x18\x03 \x01(\x03\x12\x15\n\ris_bookmarked\x18\x04 \x01(\x08\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'favicon_tracking_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _FAVICONTRACKINGSPECIFICS._serialized_start=45
  _FAVICONTRACKINGSPECIFICS._serialized_end=143
# @@protoc_insertion_point(module_scope)
