# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: history_delete_directive_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(history_delete_directive_specifics.proto\x12\x07sync_pb\"\x95\x01\n\x1fHistoryDeleteDirectiveSpecifics\x12\x37\n\x13global_id_directive\x18\x01 \x01(\x0b\x32\x1a.sync_pb.GlobalIdDirective\x12\x39\n\x14time_range_directive\x18\x02 \x01(\x0b\x32\x1b.sync_pb.TimeRangeDirective\"V\n\x11GlobalIdDirective\x12\x11\n\tglobal_id\x18\x01 \x03(\x03\x12\x17\n\x0fstart_time_usec\x18\x02 \x01(\x03\x12\x15\n\rend_time_usec\x18\x03 \x01(\x03\"D\n\x12TimeRangeDirective\x12\x17\n\x0fstart_time_usec\x18\x01 \x01(\x03\x12\x15\n\rend_time_usec\x18\x02 \x01(\x03\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'history_delete_directive_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _HISTORYDELETEDIRECTIVESPECIFICS._serialized_start=54
  _HISTORYDELETEDIRECTIVESPECIFICS._serialized_end=203
  _GLOBALIDDIRECTIVE._serialized_start=205
  _GLOBALIDDIRECTIVE._serialized_end=291
  _TIMERANGEDIRECTIVE._serialized_start=293
  _TIMERANGEDIRECTIVE._serialized_end=361
# @@protoc_insertion_point(module_scope)
