# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: history_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14history_status.proto\x12\x07sync_pb\"\x16\n\x14HistoryStatusRequest\"Z\n\x15HistoryStatusResponse\x12\'\n\x19min_poll_interval_seconds\x18\x01 \x01(\x05:\x04\x33\x36\x30\x30\x12\x18\n\x10has_derived_data\x18\x02 \x01(\x08\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'history_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _HISTORYSTATUSREQUEST._serialized_start=33
  _HISTORYSTATUSREQUEST._serialized_end=55
  _HISTORYSTATUSRESPONSE._serialized_start=57
  _HISTORYSTATUSRESPONSE._serialized_end=147
# @@protoc_insertion_point(module_scope)
