# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: loopback_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfindexeddb.leveldb.plugins.proto.chrome_sync import sync_pb2 as sync__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15loopback_server.proto\x12\x07sync_pb\x1a\nsync.proto\"\xce\x01\n\x14LoopbackServerEntity\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".sync_pb.LoopbackServerEntity.Type\x12#\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x13.sync_pb.SyncEntity\x12\x12\n\nmodel_type\x18\x03 \x01(\x03\"K\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x42OOKMARK\x10\x01\x12\r\n\tPERMANENT\x10\x02\x12\r\n\tTOMBSTONE\x10\x03\x12\n\n\x06UNIQUE\x10\x04\"\xa5\x01\n\x13LoopbackServerProto\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x16\n\x0estore_birthday\x18\x02 \x01(\x03\x12/\n\x08\x65ntities\x18\x03 \x03(\x0b\x32\x1d.sync_pb.LoopbackServerEntity\x12\x15\n\rkeystore_keys\x18\x04 \x03(\t\x12\x1d\n\x15last_version_assigned\x18\x05 \x01(\x03\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loopback_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _LOOPBACKSERVERENTITY._serialized_start=47
  _LOOPBACKSERVERENTITY._serialized_end=253
  _LOOPBACKSERVERENTITY_TYPE._serialized_start=178
  _LOOPBACKSERVERENTITY_TYPE._serialized_end=253
  _LOOPBACKSERVERPROTO._serialized_start=256
  _LOOPBACKSERVERPROTO._serialized_end=421
# @@protoc_insertion_point(module_scope)
