# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: managed_user_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmanaged_user_specifics.proto\x12\x07sync_pb\"\xd2\x01\n\x14ManagedUserSpecifics\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1b\n\x0c\x61\x63knowledged\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x12\n\nmaster_key\x18\x04 \x01(\t\x12\x15\n\rchrome_avatar\x18\x05 \x01(\t\x12\x17\n\x0f\x63hromeos_avatar\x18\x06 \x01(\t\x12\x1e\n\x16password_signature_key\x18\x07 \x01(\t\x12\x1f\n\x17password_encryption_key\x18\x08 \x01(\tB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'managed_user_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _MANAGEDUSERSPECIFICS._serialized_start=42
  _MANAGEDUSERSPECIFICS._serialized_end=252
# @@protoc_insertion_point(module_scope)
