# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: managed_user_shared_setting_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+managed_user_shared_setting_specifics.proto\x12\x07sync_pb\"k\n!ManagedUserSharedSettingSpecifics\x12\r\n\x05mu_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x1b\n\x0c\x61\x63knowledged\x18\x04 \x01(\x08:\x05\x66\x61lseB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'managed_user_shared_setting_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _MANAGEDUSERSHAREDSETTINGSPECIFICS._serialized_start=56
  _MANAGEDUSERSHAREDSETTINGSPECIFICS._serialized_end=163
# @@protoc_insertion_point(module_scope)
