# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_type_store_schema_descriptor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(model_type_store_schema_descriptor.proto\x12\x07sync_pb\"8\n\x1eModelTypeStoreSchemaDescriptor\x12\x16\n\x0eversion_number\x18\x01 \x01(\x03\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_type_store_schema_descriptor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _MODELTYPESTORESCHEMADESCRIPTOR._serialized_start=53
  _MODELTYPESTORESCHEMADESCRIPTOR._serialized_end=109
# @@protoc_insertion_point(module_scope)
