# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_type_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfindexeddb.leveldb.plugins.proto.chrome_sync import sync_pb2 as sync__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16model_type_state.proto\x12\x07sync_pb\x1a\nsync.proto\"\xb2\x01\n\x0eModelTypeState\x12\x38\n\x0fprogress_marker\x18\x01 \x01(\x0b\x32\x1f.sync_pb.DataTypeProgressMarker\x12.\n\x0ctype_context\x18\x02 \x01(\x0b\x32\x18.sync_pb.DataTypeContext\x12\x1b\n\x13\x65ncryption_key_name\x18\x03 \x01(\t\x12\x19\n\x11initial_sync_done\x18\x04 \x01(\x08\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_type_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _MODELTYPESTATE._serialized_start=48
  _MODELTYPESTATE._serialized_end=226
# @@protoc_insertion_point(module_scope)
