# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: password_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfindexeddb.leveldb.plugins.proto.chrome_sync import encryption_pb2 as encryption__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18password_specifics.proto\x12\x07sync_pb\x1a\x10\x65ncryption.proto\"\xf6\x02\n\x15PasswordSpecificsData\x12\x0e\n\x06scheme\x18\x01 \x01(\x05\x12\x14\n\x0csignon_realm\x18\x02 \x01(\t\x12\x0e\n\x06origin\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x18\n\x10username_element\x18\x05 \x01(\t\x12\x16\n\x0eusername_value\x18\x06 \x01(\t\x12\x18\n\x10password_element\x18\x07 \x01(\t\x12\x16\n\x0epassword_value\x18\x08 \x01(\t\x12\x11\n\tssl_valid\x18\t \x01(\x08\x12\x11\n\tpreferred\x18\n \x01(\x08\x12\x14\n\x0c\x64\x61te_created\x18\x0b \x01(\x03\x12\x13\n\x0b\x62lacklisted\x18\x0c \x01(\x08\x12\x0c\n\x04type\x18\r \x01(\x05\x12\x12\n\ntimes_used\x18\x0e \x01(\x05\x12\x14\n\x0c\x64isplay_name\x18\x0f \x01(\t\x12\x12\n\navatar_url\x18\x10 \x01(\t\x12\x16\n\x0e\x66\x65\x64\x65ration_url\x18\x11 \x01(\t\"(\n\x19PasswordSpecificsMetadata\x12\x0b\n\x03url\x18\x01 \x01(\t\"\xc4\x01\n\x11PasswordSpecifics\x12)\n\tencrypted\x18\x01 \x01(\x0b\x32\x16.sync_pb.EncryptedData\x12\x42\n\x1a\x63lient_only_encrypted_data\x18\x02 \x01(\x0b\x32\x1e.sync_pb.PasswordSpecificsData\x12@\n\x14unencrypted_metadata\x18\x03 \x01(\x0b\x32\".sync_pb.PasswordSpecificsMetadataB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'password_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _PASSWORDSPECIFICSDATA._serialized_start=56
  _PASSWORDSPECIFICSDATA._serialized_end=430
  _PASSWORDSPECIFICSMETADATA._serialized_start=432
  _PASSWORDSPECIFICSMETADATA._serialized_end=472
  _PASSWORDSPECIFICS._serialized_start=475
  _PASSWORDSPECIFICS._serialized_end=671
# @@protoc_insertion_point(module_scope)
