# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: priority_preference_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dfindexeddb.leveldb.plugins.proto.chrome_sync import preference_specifics_pb2 as preference__specifics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#priority_preference_specifics.proto\x12\x07sync_pb\x1a\x1apreference_specifics.proto\"O\n\x1bPriorityPreferenceSpecifics\x12\x30\n\npreference\x18\x01 \x01(\x0b\x32\x1c.sync_pb.PreferenceSpecificsB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priority_preference_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _PRIORITYPREFERENCESPECIFICS._serialized_start=76
  _PRIORITYPREFERENCESPECIFICS._serialized_end=155
# @@protoc_insertion_point(module_scope)
