# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reading_list_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1creading_list_specifics.proto\x12\x07sync_pb\"\xb2\x02\n\x14ReadingListSpecifics\x12\x10\n\x08\x65ntry_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x18\n\x10\x63reation_time_us\x18\x04 \x01(\x03\x12\x16\n\x0eupdate_time_us\x18\x05 \x01(\x03\x12\x1a\n\x12\x66irst_read_time_us\x18\x07 \x01(\x03\x12\x1c\n\x14update_title_time_us\x18\x08 \x01(\x03\x12\x44\n\x06status\x18\x06 \x01(\x0e\x32\x34.sync_pb.ReadingListSpecifics.ReadingListEntryStatus\":\n\x16ReadingListEntryStatus\x12\n\n\x06UNREAD\x10\x00\x12\x08\n\x04READ\x10\x01\x12\n\n\x06UNSEEN\x10\x02\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reading_list_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _READINGLISTSPECIFICS._serialized_start=42
  _READINGLISTSPECIFICS._serialized_end=348
  _READINGLISTSPECIFICS_READINGLISTENTRYSTATUS._serialized_start=290
  _READINGLISTSPECIFICS_READINGLISTENTRYSTATUS._serialized_end=348
# @@protoc_insertion_point(module_scope)
