# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_engine_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsearch_engine_specifics.proto\x12\x07sync_pb\"\xf6\x04\n\x15SearchEngineSpecifics\x12\x12\n\nshort_name\x18\x01 \x01(\t\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x13\n\x0b\x66\x61vicon_url\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x1c\n\x14safe_for_autoreplace\x18\x05 \x01(\x08\x12\x17\n\x0foriginating_url\x18\x06 \x01(\t\x12\x14\n\x0c\x64\x61te_created\x18\x07 \x01(\x03\x12\x17\n\x0finput_encodings\x18\x08 \x01(\t\x12+\n\x1f\x64\x65precated_show_in_default_list\x18\t \x01(\x08\x42\x02\x18\x01\x12\x17\n\x0fsuggestions_url\x18\n \x01(\t\x12\x16\n\x0eprepopulate_id\x18\x0b \x01(\x05\x12\x1c\n\x14\x61utogenerate_keyword\x18\x0c \x01(\x08\x12\x17\n\x0binstant_url\x18\x0f \x01(\tB\x02\x18\x01\x12\x15\n\rlast_modified\x18\x11 \x01(\x03\x12\x11\n\tsync_guid\x18\x12 \x01(\t\x12\x16\n\x0e\x61lternate_urls\x18\x13 \x03(\t\x12(\n\x1csearch_terms_replacement_key\x18\x14 \x01(\tB\x02\x18\x01\x12\x11\n\timage_url\x18\x15 \x01(\t\x12\x1e\n\x16search_url_post_params\x18\x16 \x01(\t\x12#\n\x1bsuggestions_url_post_params\x18\x17 \x01(\t\x12#\n\x17instant_url_post_params\x18\x18 \x01(\tB\x02\x18\x01\x12\x1d\n\x15image_url_post_params\x18\x19 \x01(\t\x12\x13\n\x0bnew_tab_url\x18\x1a \x01(\tB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_engine_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _SEARCHENGINESPECIFICS.fields_by_name['deprecated_show_in_default_list']._options = None
  _SEARCHENGINESPECIFICS.fields_by_name['deprecated_show_in_default_list']._serialized_options = b'\030\001'
  _SEARCHENGINESPECIFICS.fields_by_name['instant_url']._options = None
  _SEARCHENGINESPECIFICS.fields_by_name['instant_url']._serialized_options = b'\030\001'
  _SEARCHENGINESPECIFICS.fields_by_name['search_terms_replacement_key']._options = None
  _SEARCHENGINESPECIFICS.fields_by_name['search_terms_replacement_key']._serialized_options = b'\030\001'
  _SEARCHENGINESPECIFICS.fields_by_name['instant_url_post_params']._options = None
  _SEARCHENGINESPECIFICS.fields_by_name['instant_url_post_params']._serialized_options = b'\030\001'
  _SEARCHENGINESPECIFICS._serialized_start=43
  _SEARCHENGINESPECIFICS._serialized_end=673
# @@protoc_insertion_point(module_scope)
