# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x07sync_pb\"!\n\x12UnknownFieldsTestA\x12\x0b\n\x03\x66oo\x18\x01 \x02(\x08\".\n\x12UnknownFieldsTestB\x12\x0b\n\x03\x66oo\x18\x01 \x02(\x08\x12\x0b\n\x03\x62\x61r\x18\x02 \x02(\x08\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _UNKNOWNFIELDSTESTA._serialized_start=23
  _UNKNOWNFIELDSTESTA._serialized_end=56
  _UNKNOWNFIELDSTESTB._serialized_start=58
  _UNKNOWNFIELDSTESTB._serialized_end=104
# @@protoc_insertion_point(module_scope)
