# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: theme_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15theme_specifics.proto\x12\x07sync_pb\"\xa4\x01\n\x0eThemeSpecifics\x12\x18\n\x10use_custom_theme\x18\x01 \x01(\x08\x12#\n\x1buse_system_theme_by_default\x18\x02 \x01(\x08\x12\x19\n\x11\x63ustom_theme_name\x18\x03 \x01(\t\x12\x17\n\x0f\x63ustom_theme_id\x18\x04 \x01(\t\x12\x1f\n\x17\x63ustom_theme_update_url\x18\x05 \x01(\tB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'theme_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _THEMESPECIFICS._serialized_start=35
  _THEMESPECIFICS._serialized_end=199
# @@protoc_insertion_point(module_scope)
