# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: typed_url_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19typed_url_specifics.proto\x12\x07sync_pb\"r\n\x11TypedUrlSpecifics\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06hidden\x18\x04 \x01(\x08\x12\x12\n\x06visits\x18\x07 \x03(\x03\x42\x02\x10\x01\x12\x1d\n\x11visit_transitions\x18\x08 \x03(\x05\x42\x02\x10\x01\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'typed_url_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _TYPEDURLSPECIFICS.fields_by_name['visits']._options = None
  _TYPEDURLSPECIFICS.fields_by_name['visits']._serialized_options = b'\020\001'
  _TYPEDURLSPECIFICS.fields_by_name['visit_transitions']._options = None
  _TYPEDURLSPECIFICS.fields_by_name['visit_transitions']._serialized_options = b'\020\001'
  _TYPEDURLSPECIFICS._serialized_start=38
  _TYPEDURLSPECIFICS._serialized_end=152
# @@protoc_insertion_point(module_scope)
