# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unique_position.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15unique_position.proto\x12\x07sync_pb\"t\n\x0eUniquePosition\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x18\n\x10\x63ompressed_value\x18\x02 \x01(\x0c\x12\x1b\n\x13uncompressed_length\x18\x03 \x01(\x04\x12\x1c\n\x14\x63ustom_compressed_v1\x18\x04 \x01(\x0c\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unique_position_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _UNIQUEPOSITION._serialized_start=34
  _UNIQUEPOSITION._serialized_end=150
# @@protoc_insertion_point(module_scope)
