# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wifi_credential_specifics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fwifi_credential_specifics.proto\x12\x07sync_pb\"\xf9\x01\n\x17WifiCredentialSpecifics\x12\x0c\n\x04ssid\x18\x01 \x01(\x0c\x12\x46\n\x0esecurity_class\x18\x02 \x01(\x0e\x32..sync_pb.WifiCredentialSpecifics.SecurityClass\x12\x12\n\npassphrase\x18\x03 \x01(\x0c\"t\n\rSecurityClass\x12\x1a\n\x16SECURITY_CLASS_INVALID\x10\x00\x12\x17\n\x13SECURITY_CLASS_NONE\x10\x01\x12\x16\n\x12SECURITY_CLASS_WEP\x10\x02\x12\x16\n\x12SECURITY_CLASS_PSK\x10\x03\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wifi_credential_specifics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _WIFICREDENTIALSPECIFICS._serialized_start=45
  _WIFICREDENTIALSPECIFICS._serialized_end=294
  _WIFICREDENTIALSPECIFICS_SECURITYCLASS._serialized_start=178
  _WIFICREDENTIALSPECIFICS_SECURITYCLASS._serialized_end=294
# @@protoc_insertion_point(module_scope)
